# Generated by Django 4.1.5 on 2023-01-18 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductClasses',
            new_name='Category',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='classe',
            new_name='category',
        ),
    ]
