# Generated by Django 4.1.5 on 2023-01-20 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_rename_quantity_product_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.CharField(
                blank=True,
                choices=[('Item', 'Item'), ('Kg', 'Kg')],
                default='Item',
                max_length=30,
                null=True,
            ),
        ),
    ]
