# Generated by Django 4.1.5 on 2023-01-18 14:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_alter_sale_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='data',
            field=models.DateField(blank=True, default=django.utils.timezone.now, editable=False, null=True),
        ),
    ]
