# Generated by Django 4.1.5 on 2023-01-18 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_alter_sale_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='data',
            field=models.DateField(blank=True, null=True),
        ),
    ]
