version: "3.8"

services:
  app:
    build:
      context: . #Sets the directory for docker-compose to build.
    volumes:
      - .:/django

    # Maps port on the local machine to port on Docker image
    ports:
      - "8000:8000"
    image: app:django
    container_name:  django_container
    command: python manage.py runserver 0.0.0.0:8000