# Generated by Django 4.1.5 on 2023-01-20 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_alter_reports_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reports',
            name='stock',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
